paths:
  /users/:
    post:
      tags:
        - User
      summary: creates a new user
      produces:
      - application/json
      parameters:
      - in: body
        name: sign up
        description: It enables a user to create an account
        schema:
          $ref: '#/definitions/signUp'
      responses:
        201:
          description: An object with user details
  /users/login/:
    post:
      tags:
        - User
      summary: login a user
      produces:
        - application/json
      parameters:
      - in: body
        name: sign in
        description: It enable a user to login into an account
        schema:
          $ref: '#/definitions/login'
      responses:
        200:
          description: Welcome User you are now logged in.
        401:
          description: Username or password does not match.
        403:
          description: User is forbidden from accessing the site
        404:
          description: Username or password does not match.
  /profiles/{username}:
    put:
      tags:
        - Profiles
      summary: It updates a users profile details
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: path parameter takes the user's username
        required: true
        type: string
      - name: authorization
        in: header
        description: header takes the user's token
        required: true
        type: string
      - in: body
        name: update user profile
        description: It enables a user update their profile
        required: false
        schema:
          $ref: '#/definitions/updateUserProfile'
      responses:
        200:
          description: An object with a user updated user profile detail
        403:
          description: Unauthorized users
  /profiles/{username}/:
    get:
      tags:
        - Profiles
      summary: It returns a users profile details
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: path parameter takes the user's username
        required: true
        type: string
      responses:
        200:
          description: An object with a user profile detail
        404:
          description: User with username not found
definitions:
  signUp:
    type: object
    properties:
      user:
        type: object
        properties:
          username:
            type: string
          email:
            type: string
          password:
            type: string
          password_confirmation:
            type: string
  login:
    type: object
    properties:
      user:
        type: object
        properties:
          username:
            type: string
          password:
            type: string
  updateUserProfile:
    type: object
    properties:
      user:
        type: object
        properties:
          username:
            type: string
          email:
            type: string
          bio:
            type: string
          image:
            type: string
